### ISSUE TITLE
Reset Directives Not Working Consistently

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/phoenix#322]
Issue Tracking:

Discovery: restart of test project caused restart of Manta as expected, which caused Strelka and then vcfMerger to restart, however, vcfMerger failed because other input prepped/filtered calls from temp/ are not available.

Solution: Add reset directives to vcfMerger steps.  Local environment tested worked, however, this was on the project with "FAILED" vcfMerger process. Moved code to development and tested on dev server.  This did not result in reset working as expected as prep/filter did not get restarted as expected.

Environment Test: @bryce-turner ran test project removing 1/4 T/N exome lanes and 1/6 RNA lanes, then after completion restarted with suppressed data.  This appears to work fine.

Separately,  I used at single KHSTX exome with 2 lanes to test.  Removing 1/2 for first run and then  adding the second lane back. This failed to restart the copy of the first lane fastq and restart of the alignment.

Question:  Why did it work in one situation but not the other?  Since this was testing the FASTQ restart model in both cases there is no difference in the executed code, just a difference in the data?

Thoughts: Maybe 1/2 + 2/2 does not work but 3/4 + 4/4 works?  Maybe it only works with multiple assays and some decision tree process is not initiated by exome alone?

@bryce-turner were your projects all started from the LIMS?

@ryanrichholt Any implementation issue you can think of?

Plan to test each thought...

**Comment by PedalheadPHX** [comment]
Testing PE2_PLB, with exome, genome, RNA.  Turned off 1/2 exome, 2/5 genome, and 2/4 RNA

**Comment by PedalheadPHX** [comment]
Testing COLO829_Ashion, turned off rep2/3, then suppressed 1/2 from the constitutional and tumor samples

**Comment by PedalheadPHX** [comment]
Testing HCC1395_ATCC with single "tumor" exome, turned off 1/2 lanes

**Comment by PedalheadPHX** [comment]
Testing ALMC1_DJ with tumor only exome and RNAseq, turning off 1/2 exome lanes, leaving all RNAseq lanes

**Comment by bryce-turner** [comment]
Using updated reset directives on the merge step, testing HCC1395_ATCC with single "tumor" exome, turned off the last 1/2 lanes (L002) and then the first 1/2 lanes (L001). These were not submitted directly via LIMS due to using a different/temporary pipeline for testing (v0.5.2), instead the config file was captured and modified to be used as a custom submission on centro.

* In both reset DID work as the second copied all fastqs

* The ordering of fastq exports from LIMS does not matter here

**Comment by ryanrichholt** [comment]
It's hard for me to follow because I can't see the projects. Do you still think this is a bug in the reset directive handling, or is it just the implementation?

**Comment by bryce-turner** [comment]
We've discovered the reasoning for the apparent inconsistency, as a result I'm closing this issue. 

For our future selves, we discovered that the copy fastq code itself was actually modifying during the runs where we added back the fastq data, this ultimately was because of a shift in how the data is exported. Meaning that if we had four fastqs and added an additional two that were chronologically between any of the initial fastqs, then the initial fastqs are shifted accordingly and the new fastqs take the original place.
